config/routes.rb
Rails.application.routes.draw do
	
  get 'cupboards/new'
  get 'cupboards/edit'
  get 'stationary/new'
  get 'stationary/edit'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/new_stationary', to: 'items#new'
  get '/order_stationary/:id', to: 'items#order', :as => 'order_stationary'
  get    '/new_cupboard', to: 'cupboards#new'
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :users
  resources :items do
    member do 
      get :orders
    end
  end
  resources :cupboards
  resources :user_items do 
      member do
         put 'returning'
     end
  end

end

app/models/cupboard.rb
class Cupboard < ApplicationRecord
  # making sure the name for the cupboard is present
  validates :name, presence: true, length: { maximum: 50 }
  # a cupboard has many items, if cupboard is destroyed - destroy the items associated with it
  has_many :items, dependent: :destroy
  # a cupboard accepts nested attributes for items and allows items to be destroyed
  accepts_nested_attributes_for :items, allow_destroy: true
end

app/controllers/cupboards_controller.rb
class CupboardsController < ApplicationController

  # before displaying pages/running action make sure user is admin otherwise redirect them and throw error
  before_action :admin_user,     only: [:destroy, :new, :create, :edit]

  # displaying all cupboards
  def index
    @cupboards = Cupboard.paginate(page: params[:page])
  end

  # showing cupboard information
  def show
    @cupboard = Cupboard.find(params[:id])
  end

  # new cupboard form page
  def new
    @cupboard = Cupboard.new
    @cupboard.items.build
  end

  # edit cupboard form page
  def edit
    @cupboard = Cupboard.find(params[:id])
  end

  # editing the cupboard
  def update
    @cupboard = Cupboard.find(params[:id])
    if @cupboard.update_attributes(cupboard_params)
      flash[:success] = "Cupboard updated"
      redirect_to @cupboard
    else
      render 'edit'
    end
  end

  # creating new cupboard
  def create
    @cupboard = Cupboard.new(cupboard_params)
    if @cupboard.save
      flash[:success] = "You created a new cupboard!"
      redirect_to @cupboard
    else
      render 'new'
    end
  end

  # deleting cupboard
  def destroy
    Cupboard.find(params[:id]).destroy
    flash[:success] = "Cupboard deleted"
    redirect_to cupboards_url
  end

  private

  # params that can be passed when creating a new cupboard (nested because you can create items inside a cupboard)
	def cupboard_params
  		params.require(:cupboard).permit(:name,  
    		:items_attributes => [:name, :borrowable, :item_quantity, :_destroy]
  		)
	end

  # confirms an admin user
  def admin_user
    redirect_to(cupboards_path) unless current_user.admin?
  end
end

app/helpers/cupboards_helper.rb
module CupboardsHelper
end

app/views/cupboards/_error_messages.html.erb
<% if @cupboard.errors.any? %>
<br><br>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@cupboard.errors.count, "error") %>.
    </div>
    <ul>
    <% @cupboard.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/cupboards/_form.html.erb
<%= form_for(@cupboard) do |f| %>
<%= render 'error_messages', object: @cupboard %>

    <p>Cupboard name:</p>
    <%= f.text_field :name %><br><br>

      <%= f.fields_for :items do |item| %>
        <%= render 'item_fields', :f => item %>
      <% end %>

      <div class='links add-items'>
        <%= link_to_add_association 'Add an item', f, :items %>

        <br><br>

        <%= f.submit :submit, class: "btn btn-login" %>
      </div>

  <% end %>

app/views/cupboards/_item_fields.html.erb
<div class='nested-fields'>
        <p>Item name:</p>
        <%= f.text_field :name %><br><br>

        <p>Can this item be borrowed?</p>
        <%= f.select :borrowable, options_for_select([ ['No', false], ['Yes', true]]) %><br><br>

        <p>How many of these items are there?</p>
        <%= f.select :item_quantity, options_for_select(0..50), { prompt: "Select a quantity" } %>

        <br><br>

        <%= link_to_remove_association "Remove this item", f, class: "remove-question-link" %>

</div>

app/views/cupboards/edit.html.erb
<% provide(:title, 'Edit cupboard') %>
<% provide(:button_text, 'Create my account') %>
<h2>Edit cupboard</h2><br>


    <%= render 'form' %>

app/views/cupboards/index.html.erb
<% provide(:title, 'All cupboards') %>
<h2>All cupboards</h2><br>

<div class="page-container">

<table class="table">
  <thead>
    <tr>
      <th>Cupboard name</th>
      <th>Number of items in cupboard</th>
      <% if current_user.admin? && !current_user?(@user) %>
      <th>Other actions</th>
      <% end %>
    </tr>
  </thead>

  <tbody>

<% @cupboards.each do |cupboard| %>

<tr>

  <td><%= link_to cupboard.name, cupboard %></td>
  <td><%= cupboard.items.count %>


  <% if current_user.admin? && !current_user?(@user) %>
    <td><%= link_to "Edit", edit_cupboard_path(cupboard), class: 'btn btn-login btn-action' %> <%= link_to "Delete", cupboard, class: 'btn btn-login btn-action', method: :delete,
                                  data: { confirm: "You sure?" } %></td>
  <% end %>

</div>

</tr>
  
<% end %>

</tbody>
</table>

</div>

app/views/cupboards/new.html.erb
<% provide(:title, 'New cupboard') %>
<% provide(:button_text, 'Create new cupboard') %>
<h2>New cupboard</h2><br>

<div class="form-container">
    <%= render 'form' %>
</div>

app/views/cupboards/show.html.erb
<% provide(:title, @cupboard.name) %>

<div class="page-container">

<h2>
  <%= @cupboard.name %><br>
<h2>

<% @cupboard.items.each do |item| %>
  <h5>Product code:</h5>
  <%= link_to item.id, item_url(item) %>

  <h5>Product name:</h5>
  <%= link_to item.name, item_url(item) %><br>
  
  <br><br>
<% end %>

</div>