config/routes.rb
Rails.application.routes.draw do
	
  get 'cupboards/new'
  get 'cupboards/edit'
  get 'stationary/new'
  get 'stationary/edit'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/new_stationary', to: 'items#new'
  get '/order_stationary/:id', to: 'items#order', :as => 'order_stationary'
  get    '/new_cupboard', to: 'cupboards#new'
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :users
  resources :items do
    member do 
      get :orders
    end
  end
  resources :cupboards
  resources :user_items do 
      member do
         put 'returning'
     end
  end

end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  # a user has many orders, if the user is destroyed, destroy the orders associated with that user
  has_many :user_items, dependent: :destroy

  # Returns the hash digest of the given string.
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def self.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  # before displaying pages/running action make sure user is logged in, make sure user is the correct user and make sure user is admin otherwise redirect them and throw error
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:update, :edit]
  before_action :admin_user,     only: [:destroy]

  # display all users
  def index
    @users = User.paginate(page: params[:page])
  end

  # display information about user
  def show
    @user = User.find(params[:id])

    @user_items_all = @user.user_items
  end

  # display form for new user
  def new
    @user = User.new
  end

  # display form for editing user
  def edit
    @user = User.find(params[:id])
  end

  # create new user
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  # updating user information
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  # deleting a user
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  private
 
    # params that can be passed when creating a user
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    # confirms a logged in user
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    # confirms the correct user
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user) || current_user.admin?
    end

    # confirms an admin user
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
  
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <br>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <br>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <br>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <br>

  <%= f.submit yield(:button_text), class: "btn btn-login" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
  <div class="action-links">
    <%= link_to "edit", edit_user_path(user), class: 'btn btn-login btn-action' %> <%= link_to "delete", user, class: 'btn btn-login btn-action', method: :delete,
                                  data: { confirm: "You sure?" } %>
  </div>
  <% end %>
</li>

<br>

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<% provide(:button_text, 'Save changes') %>
<h2>Update your profile</h2><br>

<div class="form-container">
    <%= render 'form' %><br>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">Change</a>
    </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h2>All users</h2>
<br>

<%= will_paginate %>

<ul class="index-list">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>

<div class="page-container">

<h2>Sign up</h2><br>

<div class="form-container">

    <%= render 'form' %>

</div>

</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
      <h2>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h2>

      <!-- displaying the users orders - items returned and not returned and items used -->

      <h4>Items borrowed and not returned yet</h4>

      <% @user_items_all.not_returned.each do |item| %>

      <% if item.item.borrowable == true %>

      <% if current_user.id == @user.id || current_user.admin? %>
      <%= link_to item.item.name, user_item_path(item.id) %><br>
      <% else %>
      <%= item.item.name %><br>
      <% end %>

      <% end %>

      <% end %>

      <h4>Items borrowed and returned</h4>

      <% @user_items_all.returned.each do |item| %>

      <% if item.item.borrowable == true %>

      <% if current_user.id == @user.id || current_user.admin? %>
      <%= link_to item.item.name, user_item_path(item.id) %><br>
      <% else %>
      <%= item.item.name %><br>
      <% end %>

      <% end %>

      <% end %>

      <h4>Items used</h4>

      <% @user_items_all.returned.each do |item| %>

      <% if item.item.borrowable == false %>

      <% if current_user.id == @user.id || current_user.admin? %>
      <%= link_to item.item.name, user_item_path(item.id) %><br>
      <% else %>
      <%= item.item.name %><br>
      <% end %>
      
      <% end %>

      <% end %>