config/routes.rb
Rails.application.routes.draw do
	
  get 'cupboards/new'
  get 'cupboards/edit'
  get 'stationary/new'
  get 'stationary/edit'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/new_stationary', to: 'items#new'
  get '/order_stationary/:id', to: 'items#order', :as => 'order_stationary'
  get    '/new_cupboard', to: 'cupboards#new'
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :users
  resources :items do
    member do 
      get :orders
    end
  end
  resources :cupboards
  resources :user_items do 
      member do
         put 'returning'
     end
  end

end

app/models/item.rb
class Item < ApplicationRecord
  # item name must be present
  validates :name, presence: true, length: { maximum: 50 }
  # item quantity must be present
  validates :item_quantity, presence: true
  # cupboard must be present for item
  validates :cupboard, presence: true
  # an item can belong to a cupboard
  belongs_to :cupboard
  # an item accepts nested attributes for a cupboard
  accepts_nested_attributes_for :cupboard
  # an item has many orders, if item is destroyed - destroy the orders for that item as it no longer exists
  has_many :user_items, dependent: :destroy
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  # before displaying pages/running action make sure item is available, make sure user doesn't have a fine and make sure user is admin otherwise redirect them and throw error
  before_action :item_not_available, only: [:order]
  before_action :fined, only: [:order]
  before_action :admin_user,     only: [:destroy, :new, :create, :edit]

  # display all items (paginate them) and also find all current users orders
  def index 
  	@items = Item.paginate(page: params[:page])

    @user_items = current_user.user_items.pluck(:id).uniq
    @all_user_items = UserItem.where(id: @user_items)
  end


  # the new item form page
  def new
  	@item = Item.new
  	@cupboards = Cupboard.all
  end

  # creating the item
  def create
    @cupboards = Cupboard.all
    @item = Item.new(item_params)
    if @item.save
      flash[:success] = "You have created a new item!"
      redirect_to @item
    else
      render 'new'
    end
  end

  # finding out whether the current user has a fine or not
  def fined 
    @item = Item.find(params[:id])
    # finding all the users orders 
    @user_items = current_user.user_items.pluck(:id).uniq
    @all_user_items = UserItem.where(id: @user_items)

    if(@item.borrowable?)
     # if the users order created_at date is less than the date today - 2 and it hasn't been returned then display an error
     if(@all_user_items.where('created_at < ? and returned = ?', DateTime.now-2.days, false).present?)
      flash[:danger] = "Item cannot be borrowed, you currently have a fine"
      redirect_to items_path
     else

     end
   else
   end
  end

  # where you submit the order
  def order 
    @items = Item.all
    @item = Item.find(params[:id])
  end

  # showing the items information
  def show 
  	@item = Item.find(params[:id])
  end

  # the edit item form page
  def edit
  	@item = Item.find(params[:id])
  	@cupboards = Cupboard.all
  end

  # editing the item
  def update
    @item = Item.find(params[:id])
    if @item.update_attributes(item_params)
      flash[:success] = "Item updated"
      redirect_to @item
    else
      render 'edit'
    end
  end

  # deleting the item
  def destroy
    Item.find(params[:id]).destroy
    flash[:success] = "Item deleted"
    redirect_to items_url
  end

  private

  # parameters that can be passed through when item created
  def item_params
  	params.require(:item).permit(:name, :cupboard_id, :borrowable, :item_quantity)
  end

  # checking if the item quantity is 0 or not and throwing error if it is
  def item_not_available
    @item = Item.find(params[:id])
    if(@item.item_quantity == 0) 
      flash[:danger] = "Item cannot be borrowed or used - none available"
      redirect_to items_path
    end
  end

  # confirms an admin user
  def admin_user
    redirect_to(items_path) unless current_user.admin?
  end
end

app/views/items/_error_messages.html.erb
<% if @item.errors.any? %>
<br><br>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@item.errors.count, "error") %>.
    </div>
    <ul>
    <% @item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/items/_form.html.erb
<div class="form-container">

<%= form_for(@item) do |f| %>
<%= render 'error_messages', object: @item %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <br>

  <%= f.label :cupboard %>
  <%= f.collection_select :cupboard_id, @cupboards, :id, :name, :prompt => "Select a cupboard" %>

  <br><br>

  <%= f.label :borrowable, "Can this item be borrowed?" %>
  <%= f.select :borrowable, options_for_select([ ['No', false], ['Yes', true]]) %>

  <br><br>

  <%= f.label :item_quantity, "How many of these items are there?" %>
  <%= f.select :item_quantity, options_for_select(0..50), { prompt: "Select a quantity" } %>

  <br><br>

  <%= f.submit yield(:button_text), class: "btn btn-login" %>

<% end %>

</div>

app/views/items/edit.html.erb
<% provide(:title, 'Edit stationary') %>
<% provide(:button_text, 'Edit stationary') %>
<h2>Edit stationary</h2><br>

    <%= render 'form' %>

app/views/items/index.html.erb
<% provide(:title, 'All stationary') %>
<h2>All stationary</h2><br>

<div class="page-container">

<!-- display all items with information such as product code, cupboard it belongs in and a link to borrow/use the item (if in stock and user doesn't have a fine) -->

<table class="table">
  <thead>
    <tr>
      <th>Product code</th>
      <th>Item name</th>
      <th>Item quantity</th>
      <th>Cupboard item is stored in</th>
      <th>Borrow/use</th>
      <% if current_user.admin? && !current_user?(@user) %>
      <th>Other actions</th>
      <% end %>
    </tr>
  </thead>

  <tbody>

<% @items.each do |item| %>

<tr>

  <td><%= item.id %></td>
  <td><%= link_to item.name, item %></td>
  <td><%= item.item_quantity %></td>
  <td><%= link_to item.cupboard.name, item.cupboard %></td>

<% if item.item_quantity == 0 %>

<td><p>None in stock</p></td>

<% else %>

  <% if item.borrowable?  %>

    <% if(@all_user_items.where('created_at < ? and returned = ?', DateTime.now-2.days, false).present?) %>

    <td><p>You cannot borrow an item</p></td>

      <% else %>

        <td><%= link_to "Borrow item", order_stationary_url(item) %></td>

      <% end %>

  <% else %>
  <td><%= link_to "Use item", order_stationary_url(item) %></td>
  <% end %>
  
<% end %>

  <% if current_user.admin? && !current_user?(@user) %>
    <td><%= link_to "edit", edit_item_path(item), class: 'btn btn-login btn-action' %> <%= link_to "delete", item, class: 'btn btn-login btn-action', method: :delete,
                                  data: { confirm: "You sure?" } %></td>
  <% end %>
</div>

</tr>
  
<% end %>

</tbody>
</table>

</div>

app/views/items/new.html.erb
<% provide(:title, 'New stationary') %>
<% provide(:button_text, 'Create new item') %>
<h2>Create item</h2><br>

    <%= render 'form' %>

app/views/items/order.html.erb
<% provide(:title, @item.name) %>

<!-- page where you can submit order -->

<%= form_tag(user_items_path, method: "POST") do %>

  <h4>Product code:</h4>
  <p><%= @item.id %></p>

  <h4>Item name:</h4>
  <p><%= @item.name %></p>

  <h4>Can this item be borrowed?</h4>
  <% if @item.borrowable? %>
    <p>Yes</p>
  <% else %>
    <p>No</p>
  <% end %>

  <h4>Item quantity</h4>
  <p><%= @item.item_quantity %></p>

<%= fields_for :user_item do |item| %>
  <%= item.hidden_field :item_id, value: @item.id %>
  <%= item.hidden_field :user_id, value: current_user.id %>
<% end %>

<br>

<% if(@item.borrowable?) %>
  You are about to borrow 1 <%= @item.name %><br><br>
  <%= submit_tag("Borrow item", :class => "btn btn-login") %>
<% else %>
  You are about to use 1 <%= @item.name %><br><br>
  <%= submit_tag("Use item", :class => "btn btn-login") %>
<% end %>

<% end %> 

app/views/items/show.html.erb
<% provide(:title, @item.name) %>

<div class="page-container">

  <!-- display item information along with a 'borrow' or 'use' button which will redirect them to ordering page -->

        <h5>Product code:</h5>
        <p><%= @item.id %></p>

      	<h5>Item name:</h5>
        <p><%= @item.name %></p>

        <h5>Cupboard where it's stored:</h5>
        <%= link_to @item.cupboard.name, cupboard_url(@item.cupboard) %>

        <h5>Item quantity:</h5>
        <p><%= @item.item_quantity %></p>

        <h5>Can this item be borrowed?</h5>

        <% if @item.borrowable? %>
        <p>Yes</p>
        <% else %>
        <p>No</p>
        <% end %>

        <br>

        <% if @item.item_quantity == 0 %>

        <% else %>

          <% if @item.borrowable? %>
            <%= link_to "Borrow item", order_stationary_url(@item), class: 'btn btn-login' %>
          <% else %>
            <%= link_to "Use item", order_stationary_url(@item), class: 'btn btn-login'%>
          <% end %>
  
        <% end %>

</div>