config/routes.rb
Rails.application.routes.draw do
	
  get 'cupboards/new'
  get 'cupboards/edit'
  get 'stationary/new'
  get 'stationary/edit'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/new_stationary', to: 'items#new'
  get '/order_stationary/:id', to: 'items#order', :as => 'order_stationary'
  get    '/new_cupboard', to: 'cupboards#new'
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :users
  resources :items do
    member do 
      get :orders
    end
  end
  resources :cupboards
  resources :user_items do 
      member do
         put 'returning'
     end
  end

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="main-container" style="padding-right:25px; padding-left:25px;">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "RSM", root_path, id: "logo" %>
    </div>
    <nav>
      <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
        <li><%= link_to "Order history", user_items_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Cupboards <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "All cupboards", cupboards_path %></li>

              <% if current_user.admin? %>
              <li><%= link_to "New cupboard", new_cupboard_url %></li>
              <% end %>

            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Stationary <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "All stationary", items_path %></li>

              <% if current_user.admin? %>
              <li><%= link_to "New stationary", new_stationary_url %></li>
              <% end %>

            </ul>
          </li>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </div>
    </nav>
</nav>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Lato:400,700,900' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="main-container layout-container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>